# Generated by Django 5.1.2 on 2024-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True, verbose_name='Имя в телеграмме')),
                ('telegram_id', models.TextField(unique=True, verbose_name='ID в телеграмме')),
                ('coin', models.IntegerField(default=0, verbose_name='Кол-во коинов')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
