# Generated by Django 5.1.2 on 2024-10-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True)),
                ('building1_purchased', models.BooleanField(default=False)),
                ('building2_purchased', models.BooleanField(default=False)),
                ('building3_purchased', models.BooleanField(default=False)),
                ('building4_purchased', models.BooleanField(default=False)),
            ],
        ),
    ]
