# Generated by Django 5.1.2 on 2024-10-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_buildingstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingstatus',
            options={'verbose_name': 'Building Status', 'verbose_name_plural': 'Building Statuses'},
        ),
    ]
